name: amusiz
version: git
summary: Amusiz
description: "An unofficial and unpretentious Amazon Music client for Linux"
license: GPL-3.0+

base: core20
confinement: strict
grade: stable

architectures:
  - build-on: [amd64, armhf]
    run-on: [amd64, armhf]

parts:

  bottles:
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    source: https://github.com/mirkobrombin/Amusiz.git
    override-pull: |
      snapcraftctl pull
      sed -i -e 's|@PYTHON@|/usr/bin/python3|g' src/amusiz.in
    build-packages:
      - python3
      - python3-distutils
      - gettext
      - libglib2.0-dev
      - appstream-util
      - desktop-file-utils
      - gsettings-desktop-schemas-dev
      - python3-pytoml
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - libnotify4
      - libnotify-dev
      - libgtk-3-dev
    organize:
      snap/bottles/current/usr: usr

apps:
  bottles:
    command: usr/bin/amusiz
    desktop: usr/share/applications/pm.mirko.Amusiz.desktop
    extensions: [gnome-3-38]
    plugs:
      - desktop
      - desktop-legacy
      - home
      - unity7
      - x11
      - network
      - audio-playback
    slots:
      - dbus-bottles

slots:
  dbus-bottles:
    interface: dbus
    bus: session
    name: pm.mirko.Amusiz
