name: amusiz
version: git
summary: Amusiz
description: "An unofficial and unpretentious Amazon Music client for Linux"
license: GPL-3.0+

base: core20
confinement: strict
grade: stable

architectures:
  - build-on: [amd64, armhf]
    run-on: [amd64, armhf]

parts:

  amusiz:
    plugin: meson
    meson-parameters: [ --prefix=/usr ]
    source: https://github.com/mirkobrombin/Amusiz.git
    override-pull: |
      snapcraftctl pull
      sed -i -e 's|@PYTHON@|/usr/bin/python3|g' src/amusiz.in
    build-packages:
      - python3
      - python3-distutils
      - gettext
      - libglib2.0-dev
      - appstream-util
      - desktop-file-utils
      - gsettings-desktop-schemas-dev
      - python3-pytoml
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - gir1.2-webkit2-4.0
      - libnotify4
      - libnotify-dev
      - libgtk-3-dev
      - libwebkit2gtk-4.0-37
      - libgstreamer1.0-0
      - gstreamer1.0-libav
      - gstreamer1.0-x
      - gstreamer1.0-alsa
      - gstreamer1.0-gl
      - gstreamer1.0-pulseaudio
    organize:
      snap/amusiz/current/usr: usr

apps:
  amusiz:
    command: usr/bin/amusiz
    desktop: usr/share/applications/pm.mirko.Amusiz.desktop
    extensions: [gnome-3-38]
    plugs:
      - desktop
      - desktop-legacy
      - pulseaudio
      - gsettings
      - unity7
      - x11
      - network
      - network-observe
      - network-bind
      - network-status
      - audio-playback
      - dbus
      - home
    slots:
      - dbus-amusiz

slots:
  dbus-amusiz:
    interface: dbus
    bus: session
    name: pm.mirko.Amusiz
